### ISSUE TITLE
Timeout and ansible playbook hangs

### ISSUE THREAD

**Issue by mkscala** [torian/ansible-role-filebeat#12]
Hi,
 When i tried , i got timeout and increated the timeout to 1000 in ansible.cfg and the playbook hangs.
 do you know how long the filebeat install takes ?

- name : common tasks
  hosts : all
  roles :
   - common

- name  : configure and deploy filebeat server
  hosts : beats_server
  become: true
  become_method: su
  become_user: root
  roles :
   - {role: filebeat }
  tags:
   - beats

Timeout
ERROR! Timeout (12s) waiting for privilege escalation

**Comment by mkscala** [comment]
Have you tested any Elastic 5.0 and Kibana 5.0 Ansible Roles for Ubuntu 14 LTS

**Comment by torian** [comment]
The timeout depends entirely on your connection :/ not on the role.

**Comment by torian** [comment]
This role, does work on ubuntu 14 (Trusty) LTS. On the Vagrantfile on this repo, you can bring up a trusty instance, and run tests on it with:
```
vagrant up ubuntu-trusty
```

**Comment by mkscala** [comment]
the filebeat works gr8. Can you please let me know if you have Ansible Roles for Elasticsearch and Kibana 5.0 & greater versions

**Comment by torian** [comment]
I do for [elasticsearch](https://github.com/torian/ansible-role-elasticsearch)
